// app/layout.tsx (Server-Side Layout)
import { ReactNode } from 'react';
import { Metadata } from 'next';
import ClientRootLayout from './ClientRootLayout';
import './globals.css';

export const metadata: Metadata = {
  title: "Oroz",
  description: "Generated by Oroz company.",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientRootLayout>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
